/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Graph: typeof import('./components/data/Graph.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RawData: typeof import('./components/data/RawData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebSocket: typeof import('./components/data/WebSocket.vue')['default']
  }
}
